
```{r}
# EEG analysis

################################################################################
####### CMC analysis, potenitally for dissertation, conference abstract ########
################################################################################

## load libraries
library(readr) # for reading csv files
library(dplyr) # for data manipulation
library(ggplot2) # for visualization
library(tidyr) # for data tidying
library(Hmisc)
# import CSV file with subject IDs and analyze CMC over time, as well as beta vs gamma, muscle, brain region, etc
# set working directory to folder with all step9 excel files
cmcData.df <- read_csv("/Users/DOB223/Library/CloudStorage/OneDrive-MedicalUniversityofSouthCarolina/Documents/lab/studies/1eeg/TNTanalysis/allDataForAnalyzeTNT.txt")
```

```{r}
## sanity check to assess if the import in matlab was done correctly

# first, check how many rows there are per subject
summary_by_subject <- cmcData.df %>%
    group_by(Subject) %>%
    dplyr::summarise(n_rows = n()) %>%
    arrange(n_rows)
# bar graph of it
ggplot(summary_by_subject, aes(x = Subject, y = n_rows)) +
    geom_bar(stat = "identity", fill = "steelblue") +
    theme_minimal() +
    labs(
        title = "Rows per Subject",
        x = "Subject",
        y = "Number of Rows"
    )
```
################################################
########### descriptive statistics #############
################################################
```{r}
# basic descriptives of cmc_data_full
summary(cmcData.df)
describe(cmcData.df)

# check for missing values
missing_values <- sapply(cmcData.df, function(x) sum(is.na(x)))
print(missing_values)

# WMFT
ggplot(distinct(cmcData.df, Subject, .keep_all = TRUE), 
       aes(x = `WMFTavgHand`)) + 
  geom_histogram(binwidth = 10) +
  labs(
    title = "Distribution of WMFT PRE Average Hand Scores",
    x = "WMFT PRE Average Hand Score",
    y = "Number of Subjects"
  )
```
######################################################
### Histogram of the Pre CMC data across all subjects, according to connection
######################################################
```{r}
# Pre, NoVib, Beta, Prep
# first is PML (lesioned premotor cortex, PM)
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "NoVib" & Band == "Beta" & Phase == "Prep"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, NoVib, Beta, Prep",
        x = "CMC value",
        y = "count"
    )
# Pre, NoVib, Gamma, Prep
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "NoVib" & Band == "Gamma" & Phase == "Prep"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, NoVib, Gamma, Prep",
        x = "CMC value",
        y = "count"
    )

# Pre, Vib, Beta, Prep
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "Vib" & Band == "Beta" & Phase == "Prep"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, Vib, Beta, Prep",
        x = "CMC value",
        y = "count"
    )

# Pre, Vib, Gamma, Prep
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "Vib" & Band == "Gamma" & Phase == "Prep"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, Vib, Gamma, Prep",
        x = "CMC value",
        y = "count"
    )

# they all look pretty normally distributed so far on visual inspection

# Pre, NoVib, Beta, Exe
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "NoVib" & Band == "Beta" & Phase == "Exe"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, NoVib, Beta, Exe",
        x = "CMC value",
        y = "count"
    )

# Pre, NoVib, Gamma, Exe
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "NoVib" & Band == "Gamma" & Phase == "Exe"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, NoVib, Gamma, Exe",
        x = "CMC value",
        y = "count"
    )

# Pre, Vib, Beta, Exe
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "Vib" & Band == "Beta" & Phase == "Exe"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, Vib, Beta, Exe",
        x = "CMC value",
        y = "count"
    )

# Pre, Vib, Gamma, Exe
ggplot(
    filter(cmc_data_full, timePoint == "Pre" & Condition == "Vib" & Band == "Gamma" & Phase == "Exe"), 
    aes(x = PML, fill = Muscle)
 ) +
    geom_histogram(binwidth = 0.01, position = "dodge") +
    labs(
        title = "Distribution of CMC values at Pre, Vib, Gamma, Exe",
        x = "CMC value",
        y = "count"
    )

# still looks pretty normally distributed..
```

Boxplots 

```{r}
# by timepoint and frequency band, interested in PML
ggplot(cmc_data_full, aes(x = timePoint, y = PML, fill = Band)) +
    geom_boxplot() +
    theme_minimal() +
    labs(
        title = "CMC by Time Point and Frequency Band",
        x = "Time Point",
        y = "CMC - PML"
    ) +
    facet_wrap(~Muscle)

##############################
########## Violins ###########
##############################

p <- ggplot(ToothGrowth, aes(x=dose, y=len)) + 
  geom_violin(trim=FALSE)
p + stat_summary(fun.data="mean_sdl", mult=, 
                 geom="crossbar", width=0.2 )
p + stat_summary(fun.data=mean_sdl, mult=1, 
                 geom="pointrange", color="red")

# M1L - by timePoint and Frequency
p <- ggplot(cmcData.df, aes(x = timePoint, y = M1L, color = Band)) +
  geom_violin(trim = FALSE)
p + stat_summary(fun.data="mean_sdl",mult=2,
                 geom="crossbar",width=2)
p + stat_summary(fun.data=mean_sdl, mult=2, 
                 geom="pointrange", color="red")

  
# PML - by timePoint and Frequency
ggplot(cmcData.df, aes(x = timePoint, y = PML, color = Band)) + 
  geom_violin()

```

LMM, CMC over all subjects, according to connection
```{r}
# load libs for it
libs <- c('lme4', 'lmerTest', 'performance','dplyr', 'car',
          'sjPlot','parameters','easystats') # needed if loading data in and not starting at top of script.
lapply(libs, require, character.only = TRUE)  

```

```{r}
model1 <- lmer(WFMTavgTime ~ 
                (BrainRegion*Muscle*Coh*Band) + session + group +
                (Coh | session),
                data = dplyr::sample_frac(cmcData.df, 0.3)
               )

model12 <- lmer(WFMTavgTime ~ 
                (BrainRegion*Muscle*Coh) + session +
                (Subject | session),
                data = dplyr::sample_frac(cmcData.df, 0.3)
               )

# Anova(model1, type = 'III')
# anova(model1, model12)


model2 <- lmer(ARATscore ~ 
                (BrainRegion*Muscle*Coh) + session +
                (Coh | session),
                data = dplyr::sample_frac(cmcData.df, 0.3
               )
model21 <- lmer(ARATscore ~ 
                (BrainRegion*Muscle*Coh) + session +
                (Subject | session),
                data = dplyr::sample_frac(cmcData.df, 0.3)
               )
# Anova(model2, type = 'III')

```


